version: '3.8'

services:
  web:
    build: .
    container_name: ceylonfashion_web
    ports:
      - "6070:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
      - MYSQL_DATABASE=sahan
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    container_name: ceylonfashion_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sahan
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sahan.sql:/docker-entrypoint-initdb.d/sahan.sql  # auto-import your DB

volumes:
  db_data:
